version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo_db'
    environment:
    - MONGO_INITDB_DATABASE=prueba
    - MONGO_INITDB_ROOT_USERNAME=usuario
    - MONGO_INITDB_ROOT_PASSWORD=secreto
    volumes:
    - ./mongo-volume:/data/db
    ports:
    - '27017-27019:27017-27019'
